### ISSUE TITLE
Report page - Not shot form icons

### ISSUE THREAD

**Issue by StephanyJade** [Haidoe/arc#251] opened 2023-07-31 18:07 UTC
## Bug Report

**Reporter: ❗️**
 @StephanyJade 

**Describe the bug: ❗️**
In mobile view, when seeing the Not Shot Form, the icons to delete and edit are too small. For accesibility, the icons mus be at least 24x24px

**Screenshots or Video**
![image](https://github.com/Haidoe/arc/assets/128421316/3039b2e1-ede7-448e-b663-7d1adde108fc)

**Expected behavior:  ❗️**
Increase the size to 24x24px

**Actual behavior:  ❗️**
Icons in 12x12px

**Additional context:**

**Follow up checklist:  ❗️**
- [ ]  Add Assignee
- [ ]  Label priority ( priority-low, priority-medium, priority-high )
- [ ]  Label Milestone ( Alpha, Beta  )
- [ ]  Label Issue Type ( Style, Code, API  )

**Comment by ksdhir** [comment] 2023-08-01 23:32
fixed and duplicate of #252

**Closed as completed by ksdhir** 2023-08-01 23:32 UTC
Labels: priority-high, style, code, fix
